baseurl = "https://www.phil-azar.com/"
title = "Phil Azar"
copyright = "Copyright &copy; 2018 -  Big Global Tech Business Corp. LLC. &trade;"
canonifyurls = true
theme = "hugo-kiera"
languageCode ="en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true



disqusShortname = "phil-azar"
googleAnalytics = "UA-113127371-1"

[author]
    name = "Phil Azar"
    github = "filetczar"
    linkedin = "phil-azar-87aa6779/"
    twitter = "filetczar"

[params]
    tagline = "Super good at words"

[permalinks]
    Stories = "/:slug/"







